import Head from "next/head";
import MotionWrapper from "@/components/motion";
import Layout from "@/components/layout";

export default function Ramen() {
  return (
    <>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <Layout>
        <h1>Full Stack Ramen</h1>
      </Layout>
    </>
  );
}
