import Head from "next/head";
import Layout from "@/components/layout";
import Image, { StaticImageData } from "next/image";
import shin from "@/images/ramen1.jpeg";
import costco from "@/images/ramen2.jpeg";
import topramen from "@/images/ramen3.jpeg";

type RamenObject = {
  name: string;
  desc: string;
  img: StaticImageData;
};

const RamenList: RamenObject[] = [
  {
    name: "Shin Ramen",
    desc: "The best instant ramen on the market. Hits just right when you need a good spicy broth and perfectly chewy noodles. Definitely the bougiest on the list.",
    img: shin,
  },
  {
    name: "Costco Ramen",
    desc: "Costco Ramen is a very close second. It has a much richer broth than the Shin Ramen, and the spicy paste that is included is more than decent as well. Still, something about it just doesn't perfectly satisfy quite as well as the Shin Ramen. Much love to Costco Ramen though <3",
    img: costco,
  },
  {
    name: "Top Ramen",
    desc: "Top Ramen gets a special place on this list. It is not the third tastiest ramen, but in a pinch this stuff is extremely reliable. I've had too many nights of Top Ramen dinner to count. It holds a special place in my heart and I hope I never need to eat it again :D",
    img: topramen,
  },
];

export default function RamenPage() {
  return (
    <>
      <Head>
        <title>Ramen|Volchek.Dev</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <Layout>
        <h1 className="text-hunyadiyellow text-4xl">
          Top 3 Instant Ramens Of All Time (according to me)
        </h1>
        <p>
          My (biased) list of the top 3 ramen brands when you need food in a
          pinch
        </p>
        <ol className="">
          {RamenList.map((ramen) => {
            return <RamenCard ramen={ramen} key={ramen.name} />;
          })}
        </ol>
      </Layout>
    </>
  );
}

type RamenProps = {
  ramen: RamenObject;
};

const RamenCard = ({ ramen }: RamenProps) => {
  const { name, desc, img } = ramen;

  return (
    <li className="list-disc">
      <h3 className="text-4xl text-hunyadiyellow list-item">{name}</h3>
      <Image src={img} alt={name} />
      <p>{desc}</p>
    </li>
  );
};
