import Head from "next/head";
import Image from "next/image";
import climbpic from "@/images/climbpic.jpg";
import Layout from "@/components/layout";

export default function RockClimber() {
  return (
    <>
      <Head>
        <title>Rock Climber|Volchek.Dev</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <Layout>
        <h1 className="text-6xl text-hunyadiyellow">Rock Climber</h1>
        <div className="flex flex-col items-center">
          <Image
            src={climbpic}
            alt={"Definitely a picture of me"}
            className="w-1/2 h-auto"
          />
          <iframe
            src="https://drive.google.com/file/d/1hi4eBo_IbJrfi54cq3aRaUgalYiIrjm3/preview"
            width="640"
            height="480"
            allow="autoplay"
          ></iframe>
        </div>
      </Layout>
    </>
  );
}
