import Layout from "@/components/layout";
import Head from "next/head";

export default function Skater() {
  return (
    <>
      <Head>
        <title>Skater|Volchek.Dev</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <Layout>
        <h1>Full Stack Skater</h1>
      </Layout>
    </>
  );
}
